language: node_js
matrix:
  fast_finish: true
node_js:
- '10'
branches:
  only:
  - master
  # tags
  - /^\d+\.\d+\.\d+(\-beta.\d+)?$/
env:
  global:
    # GITHUB_TOKEN for yarn deploy script
    - secure: "HvogVX7tAwRIjrQ5/uw3viZgJUkkWZMpfqBk239wpuah+zjJpuuE07xvS0kgusWaJtDqS9vkd4zzu7YYemLPQu0bdkphj44QrJaF4mfqT5pN8SxSrkLD+P7cO6tHJixQlmx/nWczVTZSAgtz9CCjUCeyjC22B4CaOJ469kOuLN5JCOQRGl2S0nbBiQFDjJmkhC2P7YjAY/Xpkk8a0i3FftqD34L0lzRHfiEqQHYvtg87n6kHxW0+KXk2hc3sJbUasU1p2SfrZKUNL9SKJ0XVlLz8/Z87V/sfE8OCMfY5sdzF1L4J08Zk/CEVNflNVm3u4TkzGhL3AqzZDuhry7gcOB3ON8mJ/jq7BS6/MU/gF0N2tsseDCRaHHknn7HfPHvuO9oIRxBUCQ4knabEtSAZFwf4KPB8A+z/OmRaR+BbpEPLmM/xCqL4P+gUchizPO+eoPDXcclHoOrycpW6s13kfHiGPajVETiyc9A5Ao1ZMEjbOqP/3R0fS8/d9BTKY6VMAPKwRbza+E/bYSN1+hM9ocsHnoaCYLgWbDXqashPNHckVqltmROQaLOM19D/6VUiD+BmEplcIMSe+ekbv8BHVIYXPhe4g3mr0oe8oc/mUOAjwXlf2nn1L898IaFfnclMe+hv3WAF1BdASxyxurF7hkUUgKm2jFQfMhp4Ft19uc0="
    # REGISTRY_TOKEN for yarn cozyPublish script
    - secure: "BQ4w7L8ACQ+zcwdI4+cnUohz+9Eermz3feSkgJ5uVzdmkYhTZP0RhlIjJF546d2tapMMFlfqYyU17YnKk7+6rNgtv/eDzd/rEFCd6CvuXiCKTQ6GvP/WaxxvOomKClhrNTJ1jx6AanZf8oLOUtTkA2jCC5NxBdinSLL1uqIyh85G/c+hX467V/RDe6T5h+XmMYVH8DwVDNA+A2hbRkqTlyh8fSJgoawTOgNFzX4P4lXUVYiGj/tY+i3AESdf1Sagd0kVyHjUI6wgHkqaB6i6iqnGh3xphaFr7trXwPnG7ItrRIckniK1dTpzqQQjsyVjW2iyqXUZsf7AKLbdzKF3EWyaR3JGMlJafIqF+/OxA8vLjFWBptPEkQNtNgkZiKKCy5X/021GRwoRVEk4KSFEcvBwUh2cKJsWnUeFxvvYNBLp/6fPos7E45V2ZB1CcT5OwT3SOSmwwZtrbS8Rf6AttbvrHMfp0Y3c8W8DtYn/Ld/yanxgnpmo+4xBiq7wXn0puCAUMBeH34j6sD5Z0+UdH/ugYAJ2RNBMGHqaTQyl3OLxaEP94FSIeLjVh7uqVQP9vCiTOVQUPCTpcv0JHfB3imQOwmpvsgQvQxaKLmmX4LCglRUjDII0WoDaDo/U3WXcLyF/Ejt62s9WhIxOHYUWPUlIj2l5odHopAxSNfOAM0o="
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    skip-cleanup: true
    # deploy the build on downcloud and publish to the Cozy registry
    script: yarn cozyPublish
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    # publish stable or beta versions using Github Releases (git tag)
    script: yarn cozyPublish
    on:
      tags: true
