language: node_js
matrix:
  fast_finish: true
node_js:
- '10'
branches:
  only:
  - master
  # tags
  - /^\d+\.\d+\.\d+(\-beta.\d+)?$/
env:
  global:
    - MATTERMOST_CHANNEL="{"dev":"feat---password-mgr","beta":"feat---password-mgr,publication","stable":"feat---password-mgr,publication"}"
    # GITHUB_TOKEN for yarn deploy script
    - secure: "HvogVX7tAwRIjrQ5/uw3viZgJUkkWZMpfqBk239wpuah+zjJpuuE07xvS0kgusWaJtDqS9vkd4zzu7YYemLPQu0bdkphj44QrJaF4mfqT5pN8SxSrkLD+P7cO6tHJixQlmx/nWczVTZSAgtz9CCjUCeyjC22B4CaOJ469kOuLN5JCOQRGl2S0nbBiQFDjJmkhC2P7YjAY/Xpkk8a0i3FftqD34L0lzRHfiEqQHYvtg87n6kHxW0+KXk2hc3sJbUasU1p2SfrZKUNL9SKJ0XVlLz8/Z87V/sfE8OCMfY5sdzF1L4J08Zk/CEVNflNVm3u4TkzGhL3AqzZDuhry7gcOB3ON8mJ/jq7BS6/MU/gF0N2tsseDCRaHHknn7HfPHvuO9oIRxBUCQ4knabEtSAZFwf4KPB8A+z/OmRaR+BbpEPLmM/xCqL4P+gUchizPO+eoPDXcclHoOrycpW6s13kfHiGPajVETiyc9A5Ao1ZMEjbOqP/3R0fS8/d9BTKY6VMAPKwRbza+E/bYSN1+hM9ocsHnoaCYLgWbDXqashPNHckVqltmROQaLOM19D/6VUiD+BmEplcIMSe+ekbv8BHVIYXPhe4g3mr0oe8oc/mUOAjwXlf2nn1L898IaFfnclMe+hv3WAF1BdASxyxurF7hkUUgKm2jFQfMhp4Ft19uc0="
    # REGISTRY_TOKEN for yarn cozyPublish script
    - secure: "FWpj8hKv6cUgwNYKgmEWk1OG8iKiDbDFDCmZAvP1z3EKMwyRdlN8QMyJhsPmw9z+wE97vDDpJFw42MVKzdKLIHRS3j2Wti3pRFoEBsTJ5u2pmu8U8/jsdbDroQkV+TNmSp5/4HkOpfmmvTDhhaWULG9LQRdA51Lj2P6UYUkyRdbZtTLXCvsc3QOFir2mg9L7CSYjgM0ffUoV++xwUzpt6FcW6fTSBHRB863Jfe3pKn81SS8NyeOSdBIgxnYPc30qZ69a6aQ/hfRyY1wrxtHWtXNokN3cdoXhRoXA2+2e9GEOzkPRgcptffTZJfKfB6xzm9zYGEcKU5SsyBK2Hc4ANsUabkjt12M2zf4KGetMfLhV/k8F/iwiV8xZLmkxGGm0XkejOvXuKqam75cBHITfyFTntVy0L9klFNTF42di3ZvPI+fc4QdFQRFoK0Gkp+jINnD5cKxq4lukFXyk8/Y8EmBTcmogfldN9t/owVEk7ourUnZux3W3Semau30H18SWoOs7hoobhwDdhyoYCqwNpLYs9GiuyDXoLoxkeuWqp8hHQms270pGBFNeLe4mUYZAY6FRp+xjuoRGyWZAzTTrXGn8geHaXdx1E/k8KgJ6YE5Eq7+Sx3Nc+QorMXSLJhIkB4etH4hja0F8nB8Jp2sT5fAvcT1rxKdwYlu75tRza8M="
    # MATTERMOST_HOOK_URL for yarn cozyPublish script
    - secure: mu5HyHDpi7FG1jLtkUOd5/cAsXAAd0qXU39OnItV4goyk9kS48mJfdecninz4pU+pAMmEJAGyve9xTOpZGMWxJVL3TRsZqVzdNfxvyfYr+Znxes910y6FNZStVC0YWBee+4/xJxOEvxn4A1EhIPM5X73bvGD5c8Z8FFRQgQPiK14V2GAfKyyti46LjfO3NPpSAtdLWa0N6tV04CPMhKlvm+IaT7feKJBfoXYAaBbIjTmUvjUa10tlR02OUXD0qucBRtZpbtAdmGMWUMFtu98OO4cTkKXBNPCnyQcrpdJkJWC3wG5bdSt33bkvWoI+J1wWbqM5a6nUsfdUBBGaBC9hy/7QN2WFsTDOMQ46g1yiooXM1CMCZjgBqO7zzGK5lHKwBYGDFPXlSbhugj5vpTnrU/CE0rvAJG4vMmkU+C7uQo1HaYFZvdz2/pSTz4yavCduRVcG1h8Tpf5+tC7OoI8UR2YYWINuragjSVn0f/+sgin29k3Hpd4LphmYQXigEpWF9O3b2nT7s7+9BA9nsvaAN44AQqgrp3nqRUZEgV5w8Wu/XyghkWNtOYCcC+lvdFD97sYnf0lCFh8RZGbGifkta9WwVJDxTmCc5EXOrcLjZVDcboTKi1UFXRski5Y3qGZZxpn5Fh3FEvfZJ6zOeDLe7gUSRo+eqfACtmtqj+f3Lk=
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn lint
  - yarn test
  - yarn build
before_install:
  - if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then openssl aes-256-cbc -K $encrypted_7f483868d5a5_key -iv $encrypted_7f483868d5a5_iv -in id_rsa_downcloud_passwords.enc -out id_rsa_downcloud_passwords -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then eval "$(ssh-agent -s)"; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then chmod 600 id_rsa_downcloud_passwords; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" != "false" ]; then ssh-add id_rsa_downcloud_passwords; fi
before_deploy:
  - yarn add cozy-app-publish
deploy:
  - provider: script
    skip_cleanup: true
    # deploy the build on downcloud and publish to the Cozy registry
    script: yarn cozyPublish
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    # publish stable or beta versions using Github Releases (git tag)
    script: yarn cozyPublish
    on:
      tags: true
